name: "Python Bindings Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: build-python-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-tests:
    name: "Test Python bindings"
    strategy:
      matrix:
        os: [ 'ubuntu-24.04', 'macos-15-intel', 'macos-26' ]
        python: [ '3.10', '3.11', '3.12', '3.13' ]

    runs-on: ${{ matrix.os }}
    env:
      INSTALL_PREFIX: "/usr/local"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Python ${{ matrix.python }}"
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      # Install platform build dependencies
      - name: "Install system packages (Ubuntu)"
        if: startsWith(matrix.os, 'ubuntu-')
        run: sudo apt-get update && sudo apt-get install -y ninja-build g++ cmake

      - name: "Setup Homebrew (macOS)"
        if: startsWith(matrix.os, 'macos-')
        uses: Homebrew/actions/setup-homebrew@main

      - name: "Install system packages (macOS)"
        if: startsWith(matrix.os, 'macos-')
        run: brew install ninja gcc cmake

      # Install Python build dependencies
      - name: "Install Python build tools"
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r build-requirements.txt
          python -m pip install build pytest

      # Build wheel from pyproject.toml
      - name: "Build Python wheel"
        run: |
          python -m build
          ls -lh dist/

      # Install built wheel for testing
      - name: "Install built package"
        run: |
          pip install dist/*.whl
          python -c "import importlib.metadata; print('Installed:', importlib.metadata.version('py-capio-cl'))"

      # Run unit tests
      - name: "Run Python tests"
        run: |
          pytest -v tests/python/test_*
