name: "Python Bindings Unit Tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: build-python-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  python-tests:
    name: "Test Python bindings"
    strategy:
      matrix:
        on: [ 'ubuntu-24.04', 'macos-15-intel', 'macos-15' ]
        python: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]

    runs-on: ${{ matrix.on }}
    env:
      INSTALL_PREFIX: "/usr/local"
      CALF_LOG_DIR: ${{ github.workspace }}/capiocl_logs

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Set up Python ${{ matrix.python }}"
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}

      # Install platform build dependencies
      - name: "Install system packages (Ubuntu)"
        if: startsWith(matrix.on, 'ubuntu-')
        run: sudo apt-get update && sudo apt-get install -y ninja-build g++ cmake libcurl4-gnutls-dev libprotobuf-dev protobuf-compiler

      - name: "Setup Homebrew (macOS)"
        if: startsWith(matrix.on, 'macos-')
        uses: Homebrew/actions/setup-homebrew@main

      - name: "Install system packages (macOS)"
        if: startsWith(matrix.on, 'macos-')
        run: brew install ninja gcc cmake curl protobuf

      - name: "Create virtual environment"
        run: |
          pip install -r build-requirements.txt
          pip install -r test-requirements.txt

      # Install Python build dependencies
      - name: "Build and Install Python package"
        run: |
          mkdir -p /tmp/capio_cl_jsons
          mkdir -p /tmp/capio_cl_tomls
          cp -r tests/jsons/* /tmp/capio_cl_jsons
          cp -r tests/tomls/* /tmp/capio_cl_tomls
          pip install .

      # Run unit tests
      - name: "Run Python tests (Ubuntu)"
        if: startsWith(matrix.on, 'ubuntu-')
        run: |
          pytest -v tests/python/test_*

      - name: "Run Python tests (MacOS)"
        if: startsWith(matrix.on, 'macos-')
        run: |
          pytest -k "not test_home_node" -v tests/python/test_*

      - name: "Zip CALF logs"
        if: always()
        run: |
          if [ -d "capiocl_logs" ]; then
            cmake -E tar cf capiocl_logs.zip --format=zip capiocl_logs
          fi

      - name: "Upload CALF logs"
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('capiocl-logs-{0}-{1}', matrix.on, matrix.python) }}
          path: capiocl_logs.zip
          retention-days: 1
          if-no-files-found: ignore


      - name: "Generate coverage report"
        if: ${{ startsWith(matrix.on, 'ubuntu-') }}
        run: |
          pip install --upgrade gcovr
           gcovr                                          \
            --exclude-throw-branches                      \
            --gcov-ignore-parse-errors=negative_hits.warn \
            --exclude tests/                              \
            --xml coverage.xml                            \
            .

      - name: "Upload coverage report"
        if: ${{ startsWith(matrix.on, 'ubuntu-') }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ format('{0}-{1}-tests', matrix.on, matrix.python) }}
          path: ./coverage.xml
          retention-days: 1
          if-no-files-found: error
