name: "Python Bindings Build & Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: build-python-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-24.04'
          - 'ubuntu-24.04-arm'
          - 'macos-26-intel'
          - 'macos-26'

    env:
      CIBW_BEFORE_ALL_LINUX: >
        pip install cmake ninja
      CIBW_BEFORE_ALL_MACOS: >
        brew install ninja gcc cmake curl

      CIBW_BEFORE_BUILD: >
        pip install -r build-requirements.txt &&
        mkdir -p /tmp/capio_cl_jsons /tmp/capio_cl_tomls &&
        cp -r tests/jsons/* /tmp/capio_cl_jsons/ &&
        cp -r tests/tomls/* /tmp/capio_cl_tomls/

      CIBW_BEFORE_TEST: pip install -r test-requirements.txt

      CIBW_TEST_COMMAND_LINUX: "pytest -v {project}/tests/python/test_*"
      CIBW_TEST_COMMAND_MACOS: "pytest -k 'not test_home_node' -v {project}/tests/python/test_*"

      CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp314-*"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.15"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
